spring.config.import=optional:file:.env[.properties]
spring.application.name=managementajax
server.port=8080


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/playground
spring.datasource.username=Ash
spring.datasource.password=Ash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.springframework.security=TRACE

initialdata.insertdefaults=false

